### ISSUE TITLE
Add information to README explaining how to add to touch bar

### ISSUE THREAD

**Issue by eterps** [ivoronin/TomatoBar#1]
Add information to README explaining how to add to touch bar, or at least a hint as it is entirely unclear at the moment.

**Comment by ivoronin** [comment]
It seems pretty obvious for me. Just launch the app and new icon will appear in the rightmost panel (nearby to brightness and volume controls). Is it now working this way for you?

**Comment by rwenz3l** [comment]
Just to raise this again - yes it does, but only when there is no other app occupying that space. I have multiple Apps with touchbar integration and this one is not visible when launched later. So yeah.. would be cool to have some "screenshot" of this or some kind of guide that helps configuring this stuff.
