### ISSUE TITLE
Menu bar bug

### ISSUE THREAD

**Issue by tonykingnz** [ivoronin/TomatoBar#13]
If you stop the break timer, the time that was counting before still apear behind the tomato:
<img width="421" alt="Screen Shot 2021-11-29 at 5 45 29 PM" src="https://user-images.githubusercontent.com/30808376/143943606-784614f7-ae70-4c2e-815c-f2f3384a30d0.png">
<img width="421" alt="Screen Shot 2021-11-29 at 5 45 34 PM" src="https://user-images.githubusercontent.com/30808376/143943611-135b9474-d0e2-4b84-8d36-d3bd8c16e326.png">

Bug with the version 2.2.1 of the App running on macOS Monterey 12.0.1.

**Comment by ivoronin** [comment]
Is that happening all the time, or just occasionally?

**Comment by tonykingnz** [comment]
Sorry for not answering before. It's not always, just sometimes, generally 3-5 times in a row, then the bug stop and after a few circles get back.


![ezgif-6-c80b95b4ea](https://user-images.githubusercontent.com/30808376/146183612-3e70b89b-f2f9-4899-a95f-f6bbe10e097b.gif)

**Comment by ivoronin** [comment]
I'm sure it's macOS's fault...

**Comment by denizt** [comment]
I don't think this is an issue in the current release, it was a problem in the previous release (v2) but can't reproduce in the current release, @tonykingnz can you try with the latest v3? If it persists, maybe set the attributed title to empty on timer end too?
