### ISSUE TITLE
Hide timer + app icon

### ISSUE THREAD

**Issue by Zabriskije** [ivoronin/TomatoBar#15]
Hi folks,
is it possible to add a switch to hide the timer? It's a bit distracting.

And while I'm here, I've redone the app icon to blend better with other apps on BigSur/Monterey:

<img width="128" src="https://user-images.githubusercontent.com/101254295/160499896-7861987d-f8d9-49f8-9ac5-5bd699c5a87a.png"> <img width="128" src="https://user-images.githubusercontent.com/101254295/160502654-c7958fb8-849b-4fad-9a07-7dec9e9cc2ff.png">

Feel free to use it if you like it.

PNG + ICNS: [TomatoBar.zip](https://github.com/ivoronin/TomatoBar/files/8366910/TomatoBar.zip)

**Comment by ivoronin** [comment]
1. Thanks for the cool app icon!
2. What's your proposed behaviour on hiding the timer from the menu bar? Should current timer state (idle/work/rest) be displayed while the timer is hidden?

**Comment by denizt** [comment]
@ivoronin I had also done a similar change yesterday, for the tray bar icon I changed the alt icon to grayscale, feel free to cherry-pick and use what you like. Also added a quit button.

**Comment by Zabriskije** [comment]
> * Thanks for the cool app icon!
> * What's your proposed behaviour on hiding the timer from the menu bar? Should current timer state (idle/work/rest) be displayed while the timer is hidden?

@ivoronin I'm happy you liked the icon, and proud it's now the official one!

For the timer, I've thought about making the menu bar icon look like an actual kitchen timer when working, outlined when resting, and normal when idle; but it's a bit awful:

<img width="24" src="https://user-images.githubusercontent.com/101254295/161230191-9779ce26-70b9-42ce-85c6-1af38ba4b5a0.png"> <img width="24" src="https://user-images.githubusercontent.com/101254295/161230197-c6e5576f-0883-4910-992a-23bde7b6e80a.png"> <img width="24" src="https://user-images.githubusercontent.com/101254295/161230208-4e923804-7d62-4ecc-bf33-6df360f47b60.png">

So I think showing work/rest labels make more sense if someone wants to.

Oh, I can't preview that, but making the menu bar icon a little bit smaller would maybe make it look a little less intrusive?
I still don't know how to edit .car files, I've found [AssetCatalogThinkerer](https://github.com/insidegui/AssetCatalogTinkerer) but it's just for preview.

<img width="24" src="https://user-images.githubusercontent.com/101254295/161232131-d3265bb2-02a1-4cb1-aee7-c8c2bd351f7f.png">

It's reduced from 48x48 to 42x42, and I've adjusted the stem that was cut off at the top in the current one.
If you want to try that out, the above png is icon_16x16@3x.

Just for fun, I've also made a squared one (16x16@3x too), but I think the original looks best:

<img width="24" src="https://user-images.githubusercontent.com/101254295/161235792-2ca454d9-03d3-4793-b76b-b4df1e8cd364.png">

<hr>

@denizt I was going to propose a quit button next, good job.

**Comment by ivoronin** [comment]
The current size of the menu bar icon appears to be in line with other application icons:
![image](https://user-images.githubusercontent.com/1638389/161384065-efeb11c7-bb45-430c-b222-1ffd4f218c61.png)

**Comment by Zabriskije** [comment]
> The current size of the menu bar icon appears to be in line with other application icons:
> 
> ![image](https://user-images.githubusercontent.com/1638389/161384065-efeb11c7-bb45-430c-b222-1ffd4f218c61.png)
> 
> 

In your current configuration looks better, maybe I have to just rearrange mine.

**Comment by Zabriskije** [comment]
The icon is displayed a bit funny in v3.1.0-rc1

<img width="973" alt="Schermata 2022-04-02 alle 21 14 38" src="https://user-images.githubusercontent.com/101254295/161397958-0b8263b1-4ce8-449a-8c8a-467190b60a32.png">

**Comment by ivoronin** [comment]
What's wrong? Looks good to me.

**Comment by Zabriskije** [comment]
Take another look 👀

<img width="420" src="https://user-images.githubusercontent.com/101254295/161401045-6672579d-0f71-4790-9d19-445c38364bc8.png">

It's displayed this way at all sizes.

**Comment by ivoronin** [comment]
Fixed in [rc2](https://github.com/ivoronin/TomatoBar/releases/tag/v3.1.0-rc2)!

**Comment by Zabriskije** [comment]
Hi @ivoronin! I've updated the icon 🤓
I've modified the shadows, just a tiny bit the overall color, and also gave the stem more personality.
It's a bit more modern now.

<img width="128" src="https://user-images.githubusercontent.com/101254295/218268885-fa3c85fc-2f24-42b5-a701-ef767df0fff9.png">

**Comment by Zabriskije** [comment]
Just a ping to show you the icon above @ivoronin
