### ISSUE TITLE
Add button on notification banners/alerts to break/restart manually

### ISSUE THREAD

**Issue by shycao** [ivoronin/TomatoBar#21]

**Comment by ivoronin** [comment]
Could you provide more details?

**Comment by shycao** [comment]
Sorry for the late reply. For now there is a notification banner when a break finishes,  which disappears after seconds. So a button with "Continue" option on the banner would be really helpful to manually start a new work interval, especially when the "Stop after break" switch in setting is off.

**Comment by ivoronin** [comment]
Implemented in the latest release.
