### ISSUE TITLE
Popup arrow is getting mispositioned

### ISSUE THREAD

**Issue by ivoronin** [ivoronin/TomatoBar#23]
Popup arrow is getting mispositioned after a few show/close cycles. No idea on the cause yet. I tend to blame macOS.

Relevant source code fragment:
https://github.com/ivoronin/TomatoBar/blob/33ac66c0c4eb698849e0e292eec7ff941a3a153d/TomatoBar/App.swift#L62

Screenshot:
<img width="473" alt="Screenshot 2022-05-09 at 13 44 05" src="https://user-images.githubusercontent.com/1638389/167395045-74e2c456-d361-427b-9f94-8b86389f9b4e.png">

OS version:
```
% sw_vers
ProductName:	macOS
ProductVersion:	12.3.1
BuildVersion:	21E258
```

**Comment by voioo** [comment]
Not an SwiftUI dev at all, but maybe this can help?

**Comment by ivoronin** [comment]
Thanks! Didn't help though.

**Comment by Denpex** [comment]
Is this issue still open. I would love to help out!

**Comment by ivoronin** [comment]
Yes. The issue is still present.

**Comment by PaulDoesDev** [comment]
Can confirm I'm seeing this issue pretty consistently

**Comment by Jerry23011** [comment]
Hi, do we have any updates on this issue?
