### ISSUE TITLE
Button color in dark mode

### ISSUE THREAD

**Issue by kemie** [ivoronin/TomatoBar#24]
<img width="399" alt="Release Version v3 3 0 · ivoroninTomatoBar  2022-05-09 at 150803@2x" src="https://user-images.githubusercontent.com/1877967/167416575-f7b86fc4-be8e-41b6-a9df-4f00cd577df3.png">
This is what it looks like to me :(

**Comment by ivoronin** [comment]
What's your OS version?
Please provide a screenshot of the "General" preference pane:
<img width="658" alt="Screenshot 2022-05-09 at 18 42 42" src="https://user-images.githubusercontent.com/1638389/167446831-e3c9340d-b7f1-4c85-b121-c2bbab304c6a.png">

**Comment by kemie** [comment]
I'm on Monterey 12.3
<img width="668" alt="General  2022-05-09 at 181428@2x" src="https://user-images.githubusercontent.com/1877967/167452704-6db6880f-1fda-4e80-bf8e-c529f92e63cc.png">
