### ISSUE TITLE
TomatoBar messes up Mission Control's _Show Desktop_ function

### ISSUE THREAD

**Issue by oswaldcameron** [ivoronin/TomatoBar#36]
Mission Control has a _Show Desktop_ function, which I use a lot, especially with it being assigned as a Hot Corner. Using TomatoBar messes that up; quitting the app fixes it. 

Here's a dropbox link to a screen recorded video demonstrating the behavior: https://www.dropbox.com/s/wh2pxn02twls8u1/TomatoBar%20messes%20up%20Mission%20Control%20Show%20Desktop%20function.mov?dl=0

**Comment by Stramon1um** [comment]
Yes, I have the same issue. Quitting the app solves it

**Comment by ivoronin** [comment]
Can you try the latest build? Can't reproduce on macOS 13.0

**Comment by navinthomas** [comment]
@ivoronin Can you update the version in brew as well?

**Comment by ivoronin** [comment]
https://github.com/Homebrew/homebrew-cask/pull/136190
