### ISSUE TITLE
Feature Request: Add ability to pause timer

### ISSUE THREAD

**Issue by arjun44** [ivoronin/TomatoBar#37]
Currently, there is no way to pause the pomodoro timer. It would be a useful feature. 

By "pause" I don't mean stop, I mean temporarily pause the timer with the ability to start the timer again at the paused time.

Currently when you stop the timer and press it again it resets to the specified work time.

**Comment by sinanbozkus** [comment]
I agree. +1

**Comment by Jerry23011** [comment]
Would be a great feature

**Comment by ivoronin** [comment]
The whole purpose of pomodoro technique is "to reduce the effect of internal and external interruptions on focus and flow. A pomodoro is indivisible; when interrupted during a pomodoro, either the other activity must be recorded and postponed (using the inform – negotiate – schedule – call back strategy) or the pomodoro must be abandoned"
