### ISSUE TITLE
UI problem with localization

### ISSUE THREAD

**Issue by Jerry23011** [ivoronin/TomatoBar#43]
I'm sorry, should have built it myself before pushing request
It seems that it doens't work, and in settings, it says Tomatobar doesn't support any other languages
<img width="676" alt="截屏2022-11-25 20 39 03" src="https://user-images.githubusercontent.com/89069957/203987850-7d9ecf82-c3ad-4bb6-b671-b43447715029.png">
<img width="780" alt="截屏2022-11-25 20 37 28" src="https://user-images.githubusercontent.com/89069957/203988135-1be52851-6e36-4e88-b95e-299a2f9f91d0.png">

**Comment by ivoronin** [comment]
Try the latest prerelease build, please

**Comment by Jerry23011** [comment]
Now it works, thank you very much, I will close this issue now :)
