### ISSUE TITLE
No window is displayed in the mission control, but it takes up a certain amount of space, When I enable Group windows by application in the settings.

### ISSUE THREAD

**Issue by CreatorZZY** [ivoronin/TomatoBar#44]
No window is displayed in the mission control, but it takes up a certain amount of space, When I enable Group windows by application in the settings.
<img width="668" alt="image" src="https://user-images.githubusercontent.com/38124587/209137328-50d05157-9e33-428d-8ea5-0d4ec4c94165.png">
<img width="399" alt="image" src="https://user-images.githubusercontent.com/38124587/209137425-a714d14b-92ec-4e9c-9f67-557b661d1b1b.png">

**Comment by ivoronin** [comment]
Duplicate if #33
