### ISSUE TITLE
Any plans to add stats ? 

### ISSUE THREAD

**Issue by rkscodes** [ivoronin/TomatoBar#45]
It would be really cool to know how many pomodora was done on some particular day. Is it something this app will consider ?

**Comment by becauseim** [comment]
yes, add sprints, please
it is convenient and functional

**Comment by sn0n** [comment]
Definitely something that would be useful, but could be a bit of work..

**Comment by yoghurtdewdew** [comment]
I want a log to check how many 🍅 a day/week/month. Or just show me when I start & end a 🍅.

**Comment by ivoronin** [comment]
Duplicate of #46
