### ISSUE TITLE
Ticking sound throughout Pomodoro

### ISSUE THREAD

**Issue by VasiliMan** [ivoronin/TomatoBar#5]
Thank you for a very useful app! Is there a way to add ticking sound throughout 25 min pomodoro? (not just in the beginning)? This was the recommendation in the original Pomodoro book by Francesco Cirillo (chapter 3) and I would appreciate this option in TomatoBar. Thanks!

**Comment by ivoronin** [comment]
Can you point me to a good sound clip?

**Comment by VasiliMan** [comment]
How about kitchen timer from https://freesound.org/people/maphill/sounds/204103/ or https://freesound.org/people/dawidwmika/sounds/372515/

**Comment by ivoronin** [comment]
Please check version 2.0.0!

**Comment by VasiliMan** [comment]
Perfect, thank you!
