### ISSUE TITLE
 menu bar display abnormally.

### ISSUE THREAD

**Issue by p5ydn0** [ivoronin/TomatoBar#6]
Hello, thank you for sharing.

I encountered the following bugs during use:

![image](https://user-images.githubusercontent.com/25891214/100745637-8c259780-341a-11eb-9bc2-876abb5ecb9b.png)

**More information:**

* macOS Big Sur 11.0.1
* Tomato V2.0.2
* My menu bar is set to automatically hide.

Thank you.

**Comment by m-antis** [comment]
it's an alignment bug. for now, start the timer to reset the alignment.

**Comment by ivoronin** [comment]
Looks like something changed in Bug Sur. Can reproduce, but no idea whats going wrong yet.

**Comment by ivoronin** [comment]
Works fine in 12.0.1, can't reproduce anymore
